-- MySQL Script generated by MySQL Workbench
-- 02/06/17 12:49:40
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema wflanfreorwfan
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema wflanfreorwfan
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `wflanfreorwfan`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wflanfreorwfan`.`users` (
  `idusers` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NULL,
  `lastname` VARCHAR(45) NULL,
  `nickname` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(255) NULL,
  `birthdate` DATE NULL,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`idusers`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wflanfreorwfan`.`location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wflanfreorwfan`.`location` (
  `idlocation` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `adress` VARCHAR(45) NULL,
  `lat` FLOAT(10,6) NULL,
  `log` FLOAT(10,6) NULL,
  PRIMARY KEY (`idlocation`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wflanfreorwfan`.`event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wflanfreorwfan`.`event` (
  `idevent` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `date` DATETIME NULL,
  `location` VARCHAR(45) NULL,
  `desc` VARCHAR(45) NULL,
  `location_idlocation` INT NOT NULL,
  `users_idusers` INT NOT NULL,
  PRIMARY KEY (`idevent`),
  INDEX `fk_event_location1_idx` (`location_idlocation` ASC),
  INDEX `fk_event_users1_idx` (`users_idusers` ASC),
  CONSTRAINT `fk_event_location1`
    FOREIGN KEY (`location_idlocation`)
    REFERENCES `wflanfreorwfan`.`location` (`idlocation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_event_users1`
    FOREIGN KEY (`users_idusers`)
    REFERENCES `wflanfreorwfan`.`users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wflanfreorwfan`.`event_has_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wflanfreorwfan`.`event_has_users` (
  `event_idevent` INT NOT NULL,
  `users_idusers` INT NOT NULL,
  PRIMARY KEY (`event_idevent`, `users_idusers`),
  INDEX `fk_event_has_users_users1_idx` (`users_idusers` ASC),
  INDEX `fk_event_has_users_event_idx` (`event_idevent` ASC),
  CONSTRAINT `fk_event_has_users_event`
    FOREIGN KEY (`event_idevent`)
    REFERENCES `wflanfreorwfan`.`event` (`idevent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_event_has_users_users1`
    FOREIGN KEY (`users_idusers`)
    REFERENCES `wflanfreorwfan`.`users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wflanfreorwfan`.`games`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wflanfreorwfan`.`games` (
  `idgames` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`idgames`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wflanfreorwfan`.`articles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wflanfreorwfan`.`articles` (
  `idarticles` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL,
  `text` LONGTEXT NULL,
  `pictures` VARCHAR(255) NULL,
  `publishdate` DATE NULL,
  `author` VARCHAR(45) NULL,
  `users_idusers` INT NOT NULL,
  `actif` TINYINT(1) NULL,
  `description_pictures` VARCHAR(30) NULL,
  `description` VARCHAR(50) NULL,
  PRIMARY KEY (`idarticles`),
  INDEX `fk_articles_users1_idx` (`users_idusers` ASC),
  CONSTRAINT `fk_articles_users1`
    FOREIGN KEY (`users_idusers`)
    REFERENCES `wflanfreorwfan`.`users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wflanfreorwfan`.`event_has_games`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wflanfreorwfan`.`event_has_games` (
  `event_idevent` INT NOT NULL,
  `games_idgames` INT NOT NULL,
  PRIMARY KEY (`event_idevent`, `games_idgames`),
  INDEX `fk_event_has_games_games1_idx` (`games_idgames` ASC),
  INDEX `fk_event_has_games_event1_idx` (`event_idevent` ASC),
  CONSTRAINT `fk_event_has_games_event1`
    FOREIGN KEY (`event_idevent`)
    REFERENCES `wflanfreorwfan`.`event` (`idevent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_event_has_games_games1`
    FOREIGN KEY (`games_idgames`)
    REFERENCES `wflanfreorwfan`.`games` (`idgames`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wflanfreorwfan`.`games_has_articles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wflanfreorwfan`.`games_has_articles` (
  `games_idgames` INT NOT NULL AUTO_INCREMENT,
  `articles_idarticles` INT NOT NULL,
  PRIMARY KEY (`games_idgames`, `articles_idarticles`),
  INDEX `fk_games_has_articles_articles1_idx` (`articles_idarticles` ASC),
  INDEX `fk_games_has_articles_games1_idx` (`games_idgames` ASC),
  CONSTRAINT `fk_games_has_articles_games1`
    FOREIGN KEY (`games_idgames`)
    REFERENCES `wflanfreorwfan`.`games` (`idgames`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_games_has_articles_articles1`
    FOREIGN KEY (`articles_idarticles`)
    REFERENCES `wflanfreorwfan`.`articles` (`idarticles`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wflanfreorwfan`.`token`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wflanfreorwfan`.`token` (
  `id_token` VARCHAR(45) NOT NULL,
  `token_temp` VARCHAR(45) NULL,
  `users_idusers` INT NOT NULL,
  PRIMARY KEY (`id_token`),
  INDEX `fk_token_users1_idx` (`users_idusers` ASC),
  CONSTRAINT `fk_token_users1`
    FOREIGN KEY (`users_idusers`)
    REFERENCES `wflanfreorwfan`.`users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;





--> Vincent
--> Sonny
--> Thibaud
--> Romain
--> Pierre
